"""Exporter: Convert parsed sessions to Markdown files."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .parser import Message, dialogue_text, is_dialogue_message, parse_session
from .scanner import SOURCE_CODE, SOURCE_COWORK, SessionInfo


ROLE_LABELS = {
    "user": "User",
    "assistant": "Assistant",
    "tool_result": "Tool Result",
    "system": "System",
}


EXPORT_MODES = ("both", "minimal", "full")


def export_session(
    session: SessionInfo,
    output_dir: Path,
    now: datetime | None = None,
    mode: str = "both",
) -> list[Path]:
    """Export a session to Markdown. Returns the list of written file paths.

    Two output flavours, controlled by `mode`:
      - `<date>--<session_id>.md`       — clean dialogue: only user prompts and
                                          Claude's text replies.
      - `<date>--<session_id>.full.md`  — everything: tool calls, tool results,
                                          and any visible thinking text.

    `mode` values:
      - `"both"`    (default) — write both files
      - `"minimal"`           — write only the clean `.md` file
      - `"full"`              — write only the `.full.md` file
    """
    if mode not in EXPORT_MODES:
        raise ValueError(
            f"mode must be one of {EXPORT_MODES}; got {mode!r}"
        )
    if session.jsonl_path is None or not session.jsonl_path.exists():
        raise FileNotFoundError(
            f"Session JSONL not found for {session.session_id}"
        )

    output_dir.mkdir(parents=True, exist_ok=True)
    messages = parse_session(session.jsonl_path)
    date_prefix = _date_prefix(session, messages)
    base = f"{date_prefix}--{session.session_id}"

    written: list[Path] = []
    if mode in ("both", "minimal"):
        path = output_dir / f"{base}.md"
        path.write_text(
            render_markdown(session, messages, now=now, minimal=True),
            encoding="utf-8",
        )
        written.append(path)
    if mode in ("both", "full"):
        path = output_dir / f"{base}.full.md"
        path.write_text(
            render_markdown(session, messages, now=now, minimal=False),
            encoding="utf-8",
        )
        written.append(path)
    return written


def render_markdown(
    session: SessionInfo,
    messages: list[Message],
    now: datetime | None = None,
    minimal: bool = False,
) -> str:
    """Build the full Markdown document for a session.

    In `minimal` mode subagent transcripts are dropped entirely — they're
    almost always tool plumbing, not human-facing dialogue. In full mode
    subagents are appended after the main timeline as separate sections.
    """
    now = now or datetime.now(timezone.utc)

    visible = [m for m in messages if is_dialogue_message(m)] if minimal else messages

    branch = session.git_branch or _first_non_empty(m.git_branch for m in messages)
    model = _first_non_empty(m.model for m in messages)
    msg_count = len(visible) if minimal else (session.message_count or len(messages))

    fm_fields: dict = {
        "project": session.project,
        "session_id": session.session_id,
        "source": session.source,
        "branch": branch,
        "model": model,
        "messages": msg_count,
        "exported_at": _format_iso(now),
    }
    if minimal:
        fm_fields["mode"] = "dialogue-only"
    if session.subagent_jsonl_paths and not minimal:
        fm_fields["subagents"] = len(session.subagent_jsonl_paths)
    if session.title:
        fm_fields["title"] = session.title
    frontmatter = _render_frontmatter(**fm_fields)

    title_branch = branch or "no-branch"
    if session.title:
        header = f"# {session.title}\n\n_{session.project} / {title_branch} / {session.session_id}_\n"
    else:
        header = f"# {session.project} / {title_branch} / {session.session_id}\n"

    body = _render_body(visible, minimal=minimal)

    sections = [frontmatter, "", header, body]
    if not minimal and session.subagent_jsonl_paths:
        sections.append(_render_subagents(session.subagent_jsonl_paths))
    return "\n".join(sections).rstrip() + "\n"


_RESCUE_BUNDLE_README_EN = """\
# claude-rescue bundle

This folder is a self-contained snapshot of every Claude Code and Claude Cowork
conversation found on this machine, generated by [claude-backup](https://github.com/parallelclaw/claude-backup).

**Use it when:**
- Your Anthropic account was suspended and you need to keep working — all your
  conversations are local files (Anthropic only revokes API access, not your
  disk), so you can hand the lot to a different AI provider and pick up.
- You want to switch agents (Claude → ChatGPT, Cursor, OpenClaw, a Chinese
  hosted model) and not lose context.
- You want a portable archive that doesn't depend on Anthropic's servers.

## Files in this bundle

- `README.md` — this file
- `HANDOFF_PROMPT.md` — **the prompt to paste into your new AI agent**
- `INDEX.md` — list of every session with date, title, message count, source
- `sessions/` — full clean-dialogue transcript of every session (no tool noise)

## How to use it

**The lazy way (any chat agent — Claude.ai, ChatGPT, Cursor, etc.):**

1. Open `HANDOFF_PROMPT.md`, copy its full contents.
2. Paste into a fresh conversation with your new agent.
3. The agent acknowledges. When you reference past work, paste the relevant
   `sessions/<file>.md` into the conversation.

**The thorough way (agents that accept file uploads — Cursor, Claude Projects,
ChatGPT with Files):**

1. Drop the entire `claude-rescue-<date>/` folder as project files.
2. Paste `HANDOFF_PROMPT.md` content as the first message.
3. The agent now has the full context indexed and searchable.

The new agent will read everything you and Claude built together — projects,
decisions, ongoing work — and continue from there.

---

Generated: {generated_at}
Sessions: {session_count} ({code_count} Code, {cowork_count} Cowork)
Date range: {first_date} → {last_date}
"""


_RESCUE_BUNDLE_README_RU = """\
# claude-rescue bundle

Эта папка — самодостаточный снимок всех разговоров с Claude Code и Claude Cowork
на этой машине, собранный утилитой [claude-backup](https://github.com/parallelclaw/claude-backup).

**Используйте когда:**
- Ваш Anthropic-аккаунт заблокировали, а работать нужно дальше — все ваши
  разговоры лежат локально (Anthropic блокирует только API-доступ, не ваш
  диск), так что можно скормить весь набор другому AI-провайдеру и продолжать.
- Хочется сменить агента (Claude → ChatGPT, Cursor, OpenClaw, китайская
  хостед-модель) без потери контекста.
- Нужен портативный архив, не зависящий от серверов Anthropic.

## Файлы в пакете

- `README.md` — этот файл
- `HANDOFF_PROMPT.md` — **промпт, который вставляешь новому AI-агенту**
- `INDEX.md` — список всех сессий с датой, заголовком, числом сообщений, источником
- `sessions/` — полный чистый-диалог transcript каждой сессии (без tool-шума)

## Как использовать

**Ленивый путь (любой чат-агент — Claude.ai, ChatGPT, Cursor и т.д.):**

1. Открой `HANDOFF_PROMPT.md`, скопируй всё содержимое.
2. Вставь в новый разговор с новым агентом.
3. Агент подтверждает. Когда сошлёшься на прошлую работу — вставь нужный файл
   `sessions/<file>.md` в разговор.

**Тщательный путь (агенты с file uploads — Cursor, Claude Projects, ChatGPT с Files):**

1. Загрузи всю папку `claude-rescue-<дата>/` как файлы проекта.
2. Первым сообщением вставь содержимое `HANDOFF_PROMPT.md`.
3. У нового агента теперь весь контекст индексирован и доступен для поиска.

Новый агент прочитает всё что вы строили с Claude — проекты, решения, текущие
дела — и продолжит оттуда.

---

Создано: {generated_at}
Сессий: {session_count} ({code_count} Code, {cowork_count} Cowork)
Диапазон дат: {first_date} → {last_date}
"""


_RESCUE_HANDOFF_PROMPT_EN = """\
You are taking over from Claude as my AI collaborator. Below is the complete
record of {session_count} sessions I had with Claude across {project_count}
projects, from {first_date} to {last_date}.

Treat this bundle as the closest thing to "Claude's memory of working with me" —
my history, my preferences, my ongoing projects.

## How to use this bundle

If you can read attached files: the bundle has `INDEX.md` (session list) and
`sessions/` (one Markdown file per session). Read INDEX first to understand
the scope; consult specific session files when I reference past work.

If you only see this message: I'll paste in specific sessions when relevant.
For now, work from the index below.

## Sessions index ({session_count} total)

{sessions_index}

## Working style

Match how Claude worked with me: terse, opinionated, technical. No walls of
text. Code over prose where it fits. Ask before destructive actions. Default
to short answers; expand only when I ask for depth.

## Acknowledge

In your reply, briefly confirm:
1. You're taking over from Claude as my collaborator
2. The scope ({session_count} sessions, {first_date} to {last_date})
3. That you'll consult the bundle / wait for me to paste specifics when I
   reference past work

Then wait for my next message.
"""


_RESCUE_HANDOFF_PROMPT_RU = """\
Ты принимаешь у Claude роль моего AI-партнёра. Ниже — полная запись
{session_count} сессий, которые я провёл с Claude по {project_count} проектам,
с {first_date} по {last_date}.

Воспринимай этот пакет как самое близкое к "памяти Claude обо мне" — моя
история, мои предпочтения, мои активные проекты.

## Как пользоваться пакетом

Если можешь читать прикреплённые файлы: в пакете есть `INDEX.md` (список сессий)
и `sessions/` (один Markdown-файл на сессию). Сначала прочитай INDEX чтобы
понять объём; смотри конкретные файлы сессий когда я ссылаюсь на прошлую работу.

Если видишь только это сообщение: я буду вставлять конкретные сессии когда они
понадобятся. Пока работай по индексу ниже.

## Индекс сессий (всего {session_count})

{sessions_index}

## Стиль работы

Перенимай стиль Claude: лаконично, мнения высказывай, технический фокус.
Никаких стен текста. Код предпочитай прозе где уместно. Перед деструктивными
действиями — спрашивай. По умолчанию давай короткие ответы; разворачивай только
когда я попрошу глубже.

## Подтверди

В ответе кратко подтверди:
1. Что принимаешь у Claude роль партнёра
2. Объём ({session_count} сессий, с {first_date} по {last_date})
3. Что будешь смотреть пакет / ждать конкретики от меня когда я ссылаюсь на
   прошлую работу

Дальше жди моего следующего сообщения.
"""


_RESCUE_INDEX_HEADER_EN = "# Session index\n\nChronological order. Each line: date — source — title — messages.\n\n"
_RESCUE_INDEX_HEADER_RU = "# Индекс сессий\n\nХронологически. В строке: дата — источник — заголовок — сообщений.\n\n"


def render_rescue_index(sessions: list[SessionInfo], lang: str = "en") -> str:
    """Build the INDEX.md listing every session in the bundle."""
    header = _RESCUE_INDEX_HEADER_RU if lang == "ru" else _RESCUE_INDEX_HEADER_EN
    lines: list[str] = []
    for s in sorted(sessions, key=lambda x: (x.created or "", x.session_id)):
        date = (s.created or "").split("T")[0] or "—"
        title = s.title or s.first_prompt or "(no title)"
        msgs = s.message_count or 0
        src = "Code" if s.source == SOURCE_CODE else "Cowork"
        rescue_filename = _rescue_session_filename(s)
        lines.append(
            f"- **{date}** — *{src}* — [{title}](sessions/{rescue_filename}) ({msgs} msgs, `{s.session_id[:8]}`)"
        )
    return header + "\n".join(lines) + "\n"


def render_rescue_handoff_prompt(
    sessions: list[SessionInfo], lang: str = "auto"
) -> str:
    """Build the HANDOFF_PROMPT.md — the master meta-prompt for a new agent."""
    if lang == "auto":
        lang = _detect_bundle_language(sessions)

    template = _RESCUE_HANDOFF_PROMPT_RU if lang == "ru" else _RESCUE_HANDOFF_PROMPT_EN
    sessions_index = _render_inline_index(sessions, lang=lang)
    first_date, last_date = _date_range(sessions)
    project_count = len({s.project for s in sessions})

    return template.format(
        session_count=len(sessions),
        project_count=project_count,
        first_date=first_date,
        last_date=last_date,
        sessions_index=sessions_index,
    )


def render_rescue_readme(
    sessions: list[SessionInfo],
    generated_at: datetime | None = None,
    lang: str = "auto",
) -> str:
    """Build the bundle's README.md (the file the user themselves reads)."""
    if lang == "auto":
        lang = _detect_bundle_language(sessions)
    template = _RESCUE_BUNDLE_README_RU if lang == "ru" else _RESCUE_BUNDLE_README_EN
    first_date, last_date = _date_range(sessions)
    code_count = sum(1 for s in sessions if s.source == SOURCE_CODE)
    cowork_count = sum(1 for s in sessions if s.source == SOURCE_COWORK)
    now = generated_at or datetime.now(timezone.utc)
    return template.format(
        generated_at=_format_iso(now),
        session_count=len(sessions),
        code_count=code_count,
        cowork_count=cowork_count,
        first_date=first_date,
        last_date=last_date,
    )


def _rescue_session_filename(session: SessionInfo) -> str:
    """Stable, sortable filename: `<date>--<8-char-id>.md`."""
    date = (session.created or "").split("T")[0] or "0000-00-00"
    return f"{date}--{session.session_id[:8]}.md"


def _render_inline_index(sessions: list[SessionInfo], lang: str = "en") -> str:
    msg_word = "сообщений" if lang == "ru" else "msgs"
    lines: list[str] = []
    for s in sorted(sessions, key=lambda x: (x.created or "", x.session_id)):
        date = (s.created or "").split("T")[0] or "—"
        title = s.title or s.first_prompt or "(no title)"
        msgs = s.message_count or 0
        src = "Code" if s.source == SOURCE_CODE else "Cowork"
        sid = s.session_id[:8]
        lines.append(f"- {date} ({src}, {msgs} {msg_word}, `{sid}`) — {title}")
    return "\n".join(lines)


def _date_range(sessions: list[SessionInfo]) -> tuple[str, str]:
    dates = sorted({(s.created or "").split("T")[0] for s in sessions if s.created})
    if not dates:
        return ("—", "—")
    return (dates[0], dates[-1])


def _detect_bundle_language(sessions: list[SessionInfo]) -> str:
    """Pick 'ru' if at least half the session titles/first-prompts have Cyrillic."""
    if not sessions:
        return "en"
    cyrillic = sum(
        1 for s in sessions if _has_cyrillic((s.title or "") + " " + (s.first_prompt or ""))
    )
    return "ru" if cyrillic * 2 >= len(sessions) else "en"


_HANDOFF_TEMPLATE_EN = """\
You are continuing a conversation I started in **{source_label}**.

**Original task:** {title}
**Started:** {created}{messages_clause}

Read the transcript below, briefly acknowledge you've understood the context, then wait for my next message. Match the language and tone of the conversation.

---

{transcript}

---

(Source: `{session_id}` from {source_label}. Continue from here.)
"""


_HANDOFF_TEMPLATE_RU = """\
Ты продолжаешь разговор, который я начал в **{source_label}**.

**Исходная задача:** {title}
**Начат:** {created}{messages_clause}

Прочитай транскрипт ниже, кратко подтверди что понял контекст, и жди следующего сообщения. Сохраняй язык и тон оригинального разговора.

---

{transcript}

---

(Исходная сессия: `{session_id}` из {source_label}. Продолжай отсюда.)
"""


_SOURCE_LABEL_EN = {"code": "Claude Code", "cowork": "Claude Cowork"}
_SOURCE_LABEL_RU = {"code": "Claude Code", "cowork": "Claude Cowork"}


def _has_cyrillic(text: str) -> bool:
    return any("Ѐ" <= ch <= "ӿ" for ch in text)


def detect_handoff_language(session: SessionInfo, messages: list[Message]) -> str:
    """Pick 'ru' if the title or first user prompt is in Russian, else 'en'."""
    sample = (session.title or "") + " " + (session.first_prompt or "")
    if not sample.strip():
        sample = next(
            (m.content for m in messages if m.role == "user" and m.content),
            "",
        )
    return "ru" if _has_cyrillic(sample) else "en"


def render_handoff(
    session: SessionInfo,
    messages: list[Message],
    lang: str = "auto",
) -> str:
    """Build a paste-ready prompt that hands the conversation to another agent.

    `lang`: 'auto' (default — Cyrillic-detected), 'en', or 'ru'.
    Always uses dialogue-only content (no tool noise) so paste size stays small.
    """
    if lang == "auto":
        lang = detect_handoff_language(session, messages)

    visible = [m for m in messages if is_dialogue_message(m)]
    transcript_body = _render_body(visible, minimal=True)

    template = _HANDOFF_TEMPLATE_RU if lang == "ru" else _HANDOFF_TEMPLATE_EN
    label_map = _SOURCE_LABEL_RU if lang == "ru" else _SOURCE_LABEL_EN
    source_label = label_map.get(session.source, session.source.title())

    title = session.title or session.first_prompt or "(no title)"
    created = (session.created or "").split("T")[0] or "—"
    if len(visible) > 0:
        msg_word = "сообщений" if lang == "ru" else "messages"
        messages_clause = f" ({len(visible)} {msg_word})"
    else:
        messages_clause = ""

    return template.format(
        source_label=source_label,
        title=title,
        created=created,
        messages_clause=messages_clause,
        session_id=session.session_id,
        transcript=transcript_body.rstrip(),
    )


def _render_subagents(subagent_paths: list[Path]) -> str:
    """Render each subagent transcript as a numbered section under a divider."""
    parts: list[str] = ["", "---", "", "# Subagents", ""]
    for i, path in enumerate(sorted(subagent_paths), start=1):
        agent_id = path.stem.replace("agent-", "", 1) if path.stem.startswith(
            "agent-"
        ) else path.stem
        sub_messages = parse_session(path)
        parts.append(f"## Subagent {i}: `{agent_id}`")
        if not sub_messages:
            parts.append("_(empty)_\n")
            continue
        parts.append("")
        parts.append(_render_body(sub_messages, minimal=False))
    return "\n".join(parts)


def _render_frontmatter(**fields) -> str:
    lines = ["---"]
    for key, value in fields.items():
        lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.append("---")
    return "\n".join(lines)


_YAML_INDICATOR_PREFIXES = ("'", '"', "[", "{", "&", "*", "!", "|", ">", "%", "@", "`", "?", "-")


def _yaml_scalar(value) -> str:
    if isinstance(value, int):
        return str(value)
    s = str(value) if value is not None else ""
    if s == "":
        return '""'
    needs_quoting = (
        "\n" in s
        or '"' in s
        or ": " in s
        or " #" in s
        or s.startswith(_YAML_INDICATOR_PREFIXES)
        or s.endswith(":")
        or s.strip() != s
    )
    if needs_quoting:
        escaped = s.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return s


def _render_body(messages: list[Message], minimal: bool = False) -> str:
    if not messages:
        return "_No messages._\n"

    sections: list[str] = []
    for msg in messages:
        label = ROLE_LABELS.get(msg.role, msg.role.capitalize())
        time_str = _format_short_time(msg.timestamp)
        heading = f"## {label} ({time_str})" if time_str else f"## {label}"
        if minimal:
            text = dialogue_text(msg).rstrip()
        else:
            text = msg.content.rstrip() if msg.content else ""
        body = text or "_(empty)_"
        sections.append(f"{heading}\n{body}\n")
    return "\n".join(sections)


def _format_iso(dt: datetime) -> str:
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _format_short_time(timestamp: str) -> str:
    if not timestamp:
        return ""
    try:
        dt = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
    except ValueError:
        return timestamp
    return dt.strftime("%H:%M:%S")


def _date_prefix(session: SessionInfo, messages: list[Message]) -> str:
    candidate = session.created or _first_non_empty(m.timestamp for m in messages)
    if candidate:
        try:
            dt = datetime.fromisoformat(candidate.replace("Z", "+00:00"))
            return dt.strftime("%Y-%m-%d")
        except ValueError:
            pass
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _first_non_empty(values) -> str:
    for v in values:
        if v:
            return v
    return ""
